apiVersion: v1
kind: Service
metadata:
  namespace: sky-eye-dev-env
  name: sky-eye-user-service-k8-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort : 8081
  selector:
    app: sky-eye-user-service-app 